#!/usr/bin/perl -s

use File::Temp qw/tempfile/;

$SPOOLDIR= shift(@ARGV);
$request = shift(@ARGV);
die "usage: repp [-sleep=N.NN -timeout=N] SPOOLDIR 'rePP request or filename' [reqname]\n" unless ($request);
$reqname = shift(@ARGV);
$sleep = 0.1 unless ($sleep);
$timeout = 9 unless ($timeout);

$REQDIR = "$SPOOLDIR/request";
$REPDIR = "$SPOOLDIR/report";

if ($reqname) {
	$reqfile = "$REQDIR/$reqname";
	open($REQ,">$reqfile");
} else {
	($REQ,$reqfile) = tempfile( DIR => $REQDIR );
	$reqname = substr($reqfile,rindex($reqfile,'/')+1);
};

if (-f $request) {
	open(SRC,$request);
	$request = "";
	while (<SRC>) {
		$request .= $_;
	};
};

print $REQ $request;
chmod(0644,$REQ);
close($REQ);

$total_sleep = 0.0;
$repfile = "$REPDIR/$reqname";
while (!-e $repfile) {
	select(undef,undef,undef,$sleep);
	$total_sleep += $sleep;
	if ($total_sleep>=$timeout) {
		unlink($reqfile);
		die("timeout $timeout seconds exceeded");
	};
};

open(REP,$repfile);
while (<REP>) {
	print $_;
};
close(REP);
